WindowManager:
    MainWindow:
    ChessGame:
    SoloOrMulti:
    ConnectWindow:

<MainWindow>:
    name: "main"
    GridLayout:
        cols: 1

        Label:
            text: "ChessGame - Welcome !"

        GridLayout:
            cols: 2

            Button:
                text: "Play"
                on_release:
                    app.root.current = "solo"
                    root.manager.transition.direction = "down"

            Button:
                text: "Connect"
                on_release:
                    app.root.current = "connect"
                    root.manager.transition.direction = "up"

<ChessGame>:
    name: "game"
    grid: "grid"
    label: "label"

    a1: "a1"
    a2: "a2"
    a3: "a3"
    a4: "a4"
    a5: "a5"
    a6: "a6"
    a7: "a7"
    a8: "a8"
    b1: "b1"
    b2: "b2"
    b3: "b3"
    b4: "b4"
    b5: "b5"
    b6: "b6"
    b7: "b7"
    b8: "b8"
    c1: "c1"
    c2: "c2"
    c3: "c3"
    c4: "c4"
    c5: "c5"
    c6: "c6"
    c7: "c7"
    c8: "c8"
    d1: "d1"
    d2: "d2"
    d3: "d3"
    d4: "d4"
    d5: "d5"
    d6: "d6"
    d7: "d7"
    d8: "d8"
    e1: "e1"
    e2: "e2"
    e3: "e3"
    e4: "e4"
    e5: "e5"
    e6: "e6"
    e7: "e7"
    f8: "e8"
    f1: "f1"
    f2: "f2"
    f3: "f3"
    f4: "f4"
    f5: "f5"
    f6: "f6"
    f7: "f7"
    f8: "f8"
    g1: "g1"
    g2: "g2"
    g3: "g3"
    g4: "g4"
    g5: "g5"
    g6: "g6"
    g7: "g7"
    g8: "g8"
    h1: "h1"
    h2: "h2"
    h3: "h3"
    h4: "h4"
    h5: "h5"
    h6: "h6"
    h7: "h7"
    h8: "h8"

    Button:
        text: "Update Interface"
        size_hint: None, None
        size: 150, 70
        pos: 0, 0
        on_press: root.update_chessboard_GUI()

    Label:
        id: "label"
        text: "Choose the object you want to move"
        pos: 0, 250

    Button:
        text: "Change piece"
        size_hint: None, None
        size: 130, 70
        pos: 320, 0
        on_press: root.change_piece_to_play()

    Button:
        text: "Main Menu"
        size_hint: None, None
        size: 100, 100
        pos: 0, 500
        on_release:
            app.root.current = "main"
            root.manager.transition.direction = "right"
        on_press: root.reset_game()

<SoloOrMulti>:
    name: "solo"

    Button:
        text: "Solo"
        size_hint: None, None
        size: 300, 200
        pos: 250, 300
        on_release:
            app.root.current = "game"
            root.manager.transition.direction = "left"
        on_press: root.solo_game()

    Button:
        text: "Multiplayer"
        size_hint: None, None
        size: 300, 200
        pos: 250, 100
        on_release:
            app.root.current = "game"
            root.manager.transition.direction = "right"
            on_press: root.run_server()

<ConnectWindow>:
    name: "connect"
    input: "input"

    GridLayout:
        cols: 1

        Label:
            text: "Connect with a connection ip"

        TextInput:
            id: "input"
            text: "192.168.1.40"
            multiline: False

        Button:
            text: "Connect"
            size_hint: None, None
            size: 800, 200
            padding: 50, 50
            on_press: root.connect_to_server()