<ChessGame>
    GridLayout:
        cols: 1
        rows: 2
        size: root.width, root.height - 100

        GridLayout:
            cols: 2


            Label:
                text: "Hello"

            TextInput:
                multiline: False

            Label:
                text: "Email: "

            TextInput:
                multiline: False

        Button:
            text: "Submit"
